### ISSUE TITLE
plexyglass plugin not loading (docker-mod)

### ISSUE THREAD

**Issue by daNutzzzzz** [LizardByte/PlexyGlass#25]
### Describe the Bug

plexyglass plugin doesnt appear in Plex Plugins

### Expected Behavior

plexyglass plugin appears in Plex Plugins

### Additional Context

Docker version 17.09.1-ce, build 0bbe3ac
PlexPMS Version: 1.29.0.6244 

**Compose:**
```yml
version: '3.4'
services:
    plexpms:
        container_name: plexpms
        environment:
            - 'DOCKER_MODS=lizardbyte/plexyglass:latest'
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=Europe/London'
            - 'VERSION=docker'
            - 'UMASK_SET=022'
            - 'PLEX_CLAIM=claim-**************'
        network_mode: host
        ports:
            - '8324:8324' # (controlling Plex for Roku via Plex Companion)
            - '32400:32400' # (access to the Plex Media Server) [required]
            - '32410:32410/udp' # (for current GDM network discovery)
            - '32412:32412/udp' # (for current GDM network discovery)
            - '32413:32413/udp' # (for current GDM network discovery)
            - '32414:32414/udp' # (for current GDM network discovery)
            - '32469:32469' # (access to the Plex DLNA Server)
        volumes:
            - './Plex-PMS/config:/config'
            - './Plex-PMS/transcode:/transcode'
            - './Multimedia:/Multimedia'
        restart: unless-stopped
        image: linuxserver/plex:latest
```

**Plugin Folder:**
```txt
[./Plex-PMS/config/Library/Application Support/Plex Media Server/Plug-ins] # ls -l
total 12
drwxr-xr-x 7 docker administrators 4096 2022-10-07 12:25 PlexyGlass.bundle/
drwxr-xr-x 3 docker administrators 4096 2020-10-24 21:02 Services.bundle/
drwxr-xr-x 4 docker administrators 4096 2020-11-07 12:22 WebTools.bundle/
[./Plex-PMS/config/Library/Application Support/Plex Media Server/Plug-ins] # cd PlexyGlass.bundle/
[./Plex-PMS/config/Library/Application Support/Plex Media Server/Plug-ins/PlexyGlass.bundle] # ls -l
total 72
-rwxr-xr-x 1 docker administrators   294 2022-10-07 12:25 CHANGELOG.md*
drwxr-xr-x 6 docker administrators  4096 2022-10-07 12:25 Contents/
-rwxr-xr-x 1 docker administrators   995 2022-10-07 12:25 Dockerfile*
-rwxr-xr-x 1 docker administrators  1070 2022-10-07 12:25 DOCKER_README.md*
drwxr-xr-x 3 docker administrators  4096 2022-10-07 12:25 docs/
-rwxr-xr-x 1 docker administrators 34523 2022-10-07 12:25 LICENSE*
-rwxr-xr-x 1 docker administrators  1252 2022-10-07 12:25 README.rst*
-rwxr-xr-x 1 docker administrators   410 2022-10-07 12:25 requirements-dev.txt*
-rwxr-xr-x 1 docker administrators    73 2022-10-07 12:25 requirements.txt*
drwxr-xr-x 2 docker administrators  4096 2022-10-07 12:25 scripts/
[./Plex-PMS/config/Library/Application Support/Plex Media Server/Plug-ins/PlexyGlass.bundle] #
```
![image](https://user-images.githubusercontent.com/89404081/194547962-f1285ca8-846f-4085-8fd4-8f57d7b6e0cb.png)
